import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Projector',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
}

export default function RootLayout({ children,}: { children: React.ReactNode}) {

  return (
    <html lang="en" className="h-full">
      <body className="h-full">{children}</body>
    </html>
  );
}
